// <auto-generated />
using System;
using LyrnicsDotnetCore.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LyrnicsDotnetCore.Migrations
{
    [DbContext(typeof(LyrnicsDBContext))]
    partial class LyrnicsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LyrnicsDotnetCore.Model.Band", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("character varying(35)")
                        .HasMaxLength(35);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(35)")
                        .HasMaxLength(35);

                    b.HasKey("Id")
                        .HasName("pk_band");

                    b.ToTable("band");
                });

            modelBuilder.Entity("LyrnicsDotnetCore.Model.Song", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("BandId")
                        .IsRequired()
                        .HasColumnName("band_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("character varying(35)")
                        .HasMaxLength(35);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("character varying(35)")
                        .HasMaxLength(35);

                    b.HasKey("Id")
                        .HasName("pk_song");

                    b.HasIndex("BandId");

                    b.ToTable("song");
                });

            modelBuilder.Entity("LyrnicsDotnetCore.Model.Song", b =>
                {
                    b.HasOne("LyrnicsDotnetCore.Model.Band", "Band")
                        .WithMany("Songs")
                        .HasForeignKey("BandId")
                        .HasConstraintName("fk_song_band_band_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
